import { AdTemplate } from './types';

export const CREATIVE_STYLES = [
  "Minimalist & Clean",
  "Bold & Modern",
  "Elegant & Luxurious",
  "Playful & Vibrant",
  "Futuristic & Techy",
  "Retro & Vintage",
  "Natural & Organic",
  "Corporate & Professional",
  "Grunge & Edgy",
  "Hand-drawn & Artisanal",
];

export const CHARACTER_STYLES = [
    "Default (No specific character style)",
    "Realistic (Photorealistic people)",
    "Cartoon (Animated, friendly characters)",
    "Anime/Manga (Japanese animation style)",
    "3D Render (Pixar-like characters)",
    "Illustration (Stylized, artistic characters)",
    "Abstract (Non-representational figures)",
];

export const AD_SIZES = [
  "1080x1080 (Meta Square)",
  "1080x1920 (Meta Story)",
  "1200x628 (LinkedIn Post)",
  "1200x1200 (Square)",
  "960x1200 (Portrait)",
  "1920x1080 (Landscape)",
  "300x300 (Google Square)",
  "728x90 (Google Leaderboard)",
];

export const AD_TYPES = [
  "Brand Awareness",
  "Product Showcase",
  "Campaign Promotion",
];

export const GOOGLE_FONTS = [
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Oswald",
  "Raleway",
  "Poppins",
  "Nunito",
  "Merriweather",
  "Playfair Display",
];

export const AD_TEMPLATES: AdTemplate[] = [
  {
    id: 'template-1',
    name: 'Modern Product Showcase',
    description: 'A clean, modern look to highlight your product.',
    previewImage: 'https://placehold.co/400x400/E2E8F0/4A5568?text=Modern',
    formData: {
      creativeStyle: 'Bold & Modern',
      adType: 'Product Showcase',
      header1: 'Introducing the Future',
      description: 'Experience the next generation of technology.',
      cta: 'Learn More',
    },
  },
  {
    id: 'template-2',
    name: 'Elegant Brand Ad',
    description: 'A luxurious and elegant style for brand awareness.',
    previewImage: 'https://placehold.co/400x400/D6BCFA/4A5568?text=Elegant',
    formData: {
      creativeStyle: 'Elegant & Luxurious',
      adType: 'Brand Awareness',
      header1: 'Timeless Elegance',
      header2: 'Discover Our Collection',
    },
  },
  {
    id: 'template-3',
    name: 'Vibrant Sale Promotion',
    description: 'A playful and vibrant design to announce a sale.',
    previewImage: 'https://placehold.co/400x400/FBBF24/4A5568?text=Vibrant',
    formData: {
      creativeStyle: 'Playful & Vibrant',
      adType: 'Campaign Promotion',
      header1: 'BIG SALE',
      salePrice: '50% OFF',
      cta: 'Shop Now',
    },
  },
  {
    id: 'template-4',
    name: 'Minimalist Corporate',
    description: 'A professional and clean look for corporate messaging.',
    previewImage: 'https://placehold.co/400x400/A0AEC0/4A5568?text=Minimalist',
    formData: {
      creativeStyle: 'Minimalist & Clean',
      adType: 'Brand Awareness',
      header1: 'Innovation and Trust',
      description: 'Your reliable partner for success.',
    },
  },
  {
    id: 'template-5',
    name: 'SaaS Feature Launch',
    description: 'A bold template to announce new software features.',
    previewImage: 'https://placehold.co/400x400/4F46E5/FFFFFF?text=New+Feature',
    formData: {
      creativeStyle: 'Futuristic & Techy',
      adType: 'Campaign Promotion',
      header1: 'New Feature Unlocked',
      description: 'Boost your productivity with our latest update.',
      cta: 'Explore Now',
    },
  },
  {
    id: 'template-6',
    name: 'E-commerce Flash Sale',
    description: 'An eye-catching design for limited-time offers.',
    previewImage: 'https://placehold.co/400x400/F59E0B/FFFFFF?text=FLASH+SALE',
    formData: {
      creativeStyle: 'Bold & Modern',
      adType: 'Product Showcase',
      header1: 'FLASH SALE',
      header2: 'Up to 40% Off',
      description: "Limited time only. Don't miss out!",
      cta: 'Shop the Deal',
    },
  },
  {
    id: 'template-7',
    name: 'Podcast Episode Promo',
    description: 'A minimalist template to promote your latest episode.',
    previewImage: 'https://placehold.co/400x400/10B981/FFFFFF?text=Listen+Now',
    formData: {
      creativeStyle: 'Minimalist & Clean',
      adType: 'Brand Awareness',
      header1: 'New Episode Out Now',
      description: 'Featuring a special guest interview.',
      cta: 'Listen Now',
    },
  },
  {
    id: 'template-8',
    name: 'Luxury Real Estate',
    description: 'An elegant and luxurious ad for high-end properties.',
    previewImage: 'https://placehold.co/400x400/374151/FFFFFF?text=Luxury+Living',
    formData: {
      creativeStyle: 'Elegant & Luxurious',
      adType: 'Product Showcase',
      header1: 'Your Dream Home Awaits',
      description: 'Exclusive listing in a prime location.',
      cta: 'Schedule a Viewing',
    },
  },
  {
    id: 'template-9',
    name: 'Customer Testimonial',
    description: 'Build trust with a professional testimonial ad.',
    previewImage: 'https://placehold.co/400x400/6B7280/FFFFFF?text="A+Game+Changer!"',
    formData: {
      creativeStyle: 'Corporate & Professional',
      adType: 'Brand Awareness',
      header1: '"A Game Changer!"',
      description: '- Satisfied Customer',
      cta: 'Read More Stories',
    },
  },
   {
    id: 'template-10',
    name: 'Retro Music Event',
    description: 'A vintage-style poster for a music or cultural event.',
    previewImage: 'https://placehold.co/400x400/F56565/FFFFFF?text=Live+Music',
    formData: {
      creativeStyle: 'Retro & Vintage',
      adType: 'Campaign Promotion',
      header1: 'Retro Vibes Fest',
      header2: 'Live This Weekend',
      cta: 'Get Tickets',
    },
  },
  {
    id: 'template-11',
    name: 'Organic Food Market',
    description: 'A natural and earthy design for fresh produce or health food stores.',
    previewImage: 'https://placehold.co/400x400/48BB78/FFFFFF?text=Fresh+&+Organic',
    formData: {
      creativeStyle: 'Natural & Organic',
      adType: 'Product Showcase',
      header1: 'Purely Organic',
      description: 'Fresh from the farm to your table.',
      cta: 'Shop Fresh',
    },
  },
  {
    id: 'template-12',
    name: 'Corporate Travel Ad',
    description: 'A professional layout with a bold color overlay, perfect for B2B services.',
    previewImage: 'https://i.ibb.co/3kM2s2B/navan-ad.jpg',
    formData: {
      creativeStyle: 'Corporate & Professional',
      adType: 'Brand Awareness',
      header1: 'More window seats.',
      header2: 'Less receipts.',
      description: 'Business travel & expense management. Solved.',
    },
  },
  {
    id: 'template-13',
    name: 'AI Feature Showcase',
    description: 'A bright, modern design to highlight new AI-powered features.',
    previewImage: 'https://i.ibb.co/JqjTz3D/mailchimp-ad.jpg',
    formData: {
      creativeStyle: 'Futuristic & Techy',
      adType: 'Campaign Promotion',
      header1: 'Save time and',
      header2: 'backspace less with tools',
      description: 'powered by GPT AI',
      cta: 'Learn More',
    },
  },
  {
    id: 'template-14',
    name: 'Cyber Week Deal',
    description: 'A high-impact, energetic design for major sales events like Cyber Week.',
    previewImage: 'https://i.ibb.co/Bw2y8z2/judy-ad.jpg',
    formData: {
      creativeStyle: 'Bold & Modern',
      adType: 'Campaign Promotion',
      header1: 'CYBER WEEK',
      header2: 'SAVE $395',
      description: 'HUGE SAVINGS',
      cta: 'SEE DEAL',
    },
  },
    {
    id: 'template-15',
    name: 'Social Proof Testimonial',
    description: 'A clean, engaging layout to showcase customer testimonials and build trust.',
    previewImage: 'https://i.ibb.co/6gNVs5B/cognism-ad.jpg',
    formData: {
      creativeStyle: 'Minimalist & Clean',
      adType: 'Brand Awareness',
      header1: 'Want better open rates like Elaine?',
      description: 'Our open rates were 2-6%. Now they are 40% to 60%.',
      cta: 'You should try',
    },
  },
  {
    id: 'template-16',
    name: 'Product Comparison Ad',
    description: 'An elegant split-screen design to compare your product against alternatives.',
    previewImage: 'https://i.ibb.co/L5TxxwN/qure-ad.jpg',
    formData: {
      creativeStyle: 'Elegant & Luxurious',
      adType: 'Product Showcase',
      header1: 'All-In-One',
      header2: 'Multi-tasking Serum',
      description: 'A single serum to boost firmness, even & brighten skin tone, not multiple.',
    },
  },
  {
    id: 'template-17',
    name: 'Data-Driven Ad',
    description: 'A modern, trustworthy design that uses a large statistic to grab attention.',
    previewImage: 'https://i.ibb.co/W2zC1LV/testgorilla-ad.jpg',
    formData: {
      creativeStyle: 'Corporate & Professional',
      adType: 'Brand Awareness',
      header1: '73%',
      description: 'of companies are already using skills-based hiring. Start hiring the best with TestGorilla',
      cta: 'Book a demo',
    },
  },
];